#!/bin/sh

npm install
gulp

description=$(git describe --tags --long)
version=${description%-*}

printf "\nDescription: %s\n" $description
printf "Version: %s\n" $version

swfname="locomote_player-$version.swf"
cp -f dist/Player.swf ../smart-home-app/app/bin/$swfname
printf "\nCopied dist/Player.swf to ../smart-home-app/app/bin/$swfname.\n"
jsname="locomote_player-$version.min.js"
cp -f dist/locomote.min.js ../smart-home-app/app/libs/$jsname
printf "Copied dist/locomote.min.js to ../smart-home-app/app/libs/$jsname.\n\n"

swfname="Player.swf"
cp -f dist/Player.swf ~/Development/ngTutorial/angular-phonecat/app/$swfname
printf "\nCopied dist/Player.swf to ~/Development/ngTutorial/angular-phonecat/app/$swfname.\n"
jsname="locomote.min.js"
cp -f dist/locomote.min.js ~/Development/ngTutorial/angular-phonecat/app/$jsname
printf "Copied dist/locomote.min.js to ~/Development/ngTutorial/angular-phonecat/app/$jsname.\n\n"
